### ISSUE TITLE
Starter readiness and feeding intervals (Fig. 3.4 vs Fig 3.6)

### ISSUE THREAD

**Issue by tschaei** [hendricius/the-sourdough-framework#100]
So reading chapter 3 I'm a little confused as to how often you should feed your starter until it is ready. Figure 3.4 has you feed the starter every 24 hours, whereas in Figure 3.6 it's every 12 hours. Did I miss something? Are these two flowcharts for different situations?

**Comment by hendricius** [comment]
Good catch! Thanks.

I fixed it:

<img width="929" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/179e7849-27e6-4ea9-b5f3-933b24450016">
