### ISSUE TITLE
Typo on cover

### ISSUE THREAD

**Issue by jvalteren** [hendricius/the-sourdough-framework#101]
Hi Hendrik,

I like your content and think it is a great initiative to publish the book!

The little guy on the cover has a speech bubble with the text: 'WOW! Deliciously scientiffic'. However the word 'scientiffic' is misspelled, it should be: 'scientific' (only one f). Also see: https://www.wordnik.com/words/scientific

<img width="171" alt="Screenshot 2023-05-25 at 12 53 46" src="https://github.com/hendricius/the-sourdough-framework/assets/10142396/b8f1f5d1-0c5b-40ca-a639-df5454ae875b">

Keep up the great work!

Greetings from the Netherlands,
Jonathan

**Comment by hendricius** [comment]
Thank you! I will fix that right away :-)
