### ISSUE TITLE
what is the export_figures target here for in makefile?

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#119]
Commit e0d54220 says it is about having nice .png, but .png appears automagically and this is not called anyway.

Any objections I get rid of it?

**Comment by hendricius** [comment]
@cedounet ok - if they are still built, no problem. I used the export to make this file: https://ko-fi.com/s/739d0b7532

**Comment by cedounet** [comment]
On Thu, Jun 08, 2023 at 02:24:16AM -0700, Hendrik Kleinwaechter wrote:
> @cedounet ok - if they are still built, no problem. I used the export to make this file: https://ko-fi.com/s/739d0b7532

MMMhhh I was planning to get rid of the TikZ being built separately,
i.e. use \input instead of include the pdf, but you closed it.  I
understand you want to be able to export your diagrams as png for the
website. I can probably get both though if that is needed.

Thanks

**Comment by hendricius** [comment]
@cedounet sweet. It seemed that I could only achieve persistent display of TikZ graphics when including a built PDF/PNG for display in the main book. Only then the epub, mobi and azw3 formats looked great. When not doing it like that sometimes the text was smaller, sometimes some of the rectangles bigger, sometimes arrows were missing. I am not 100% sure how \input works, if it generates a different image, or if the source code is included? If the source is included I assume the final epub will have a SVG again and not a png. This could cause display issues.

**Comment by cedounet** [comment]
On Thu, Jun 08, 2023 at 02:39:15AM -0700, Hendrik Kleinwaechter wrote:
> @cedounet sweet. It seemed that I could only achieve persistent
> display of TikZ graphics when including a built PDF/PNG for display in
> the main book. Only then the epub, mobi and azw3 formats looked great.
> When not doing it like that sometimes the text was smaller, sometimes
> some of the rectangles bigger, sometimes arrows were missing.

OK, so ebook looked weird, but pdf was fine?  Just to make sure i get
this right.

>  I am not 100% sure how \input works, if it generates a different
>  image, or if the source code is included? If the source is included I
>  assume the final epub will have a SVG again and not a png. This could
>  cause display issues.
yeah input is dumb, same as #include in C.  Copy pastes inside the main
file.  I will try to reproduce the problem first.

Thanks

C/

**Comment by hendricius** [comment]
@cedounet yep. That is correct. PDF was fine as it didn't render a SVG internally. Inside of the ebooks SVGs were used in the HTML file. Each of the ebook readers would display the SVGs slightly differently.
