### ISSUE TITLE
Do we need sans-serif ebooks ?

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#131]
The nice thing about ebook is that you can change font size and type of font... pick the one you like even.  as we spend most of the build time doing ebooks, my polar bear friend is asking if we should really do it?  pdf of course, but for ebooks... ?  Had i thought of that _before_ fixing the makefile maybe i would have a strong opinion, but now I am fine with either.

**Comment by hendricius** [comment]
It's a valid comment. Maybe we can switch to sans serif only? I was asked from a reader with accessibility issues. He could not easily read the serif version. Maybe it's better to only build sans-serif. Open to suggestions.

**Comment by cedounet** [comment]
On Wed, Jun 28, 2023 at 11:34:19AM -0700, Hendrik Kleinwaechter wrote:
> It's a valid comment. Maybe we can switch to sans serif only? I was
> asked from a reader with accessibility issues. He could not easily
> read the serif version. Maybe it's better to only build sans-serif.
> Open to suggestions.

I dislike sans-serif when there is a lot of text... I find it hard to
read.  My preference would be:

    book_serif.pdf
    book_sans_serif.pdf
    book_sans_serif.epub/azw3/...

we can also leave the code for generating it all, just not build it by
default.

C/

**Comment by hendricius** [comment]
That's a good idea. Maybe we only build it in the github action that uploads the documents to AWS S3 on merge to main?

**Comment by cedounet** [comment]
we want CI to catch errors early though ...  I have it a go and i don;t understand why we don't save any time.  I did not look at logs though

**Comment by cedounet** [comment]
Actually it goes down to 4m19 or from 10 to 12 min...

**Comment by hendricius** [comment]
That's pretty impressive 😎 . I agree - we want to catch the errors. But - building sans serif I assume should not cause that many errors? I assume running this check only on merge to main should be OK?

**Comment by cedounet** [comment]
Famous last words 🧐

I do not find tex4ht to be super robust, an impressive piece of work for sure, but LaTeX macro tend to break some seemingly unrelated things in another package relatively often…. Maybe I am being unfair but tex4ht is newer and seems to suffer from more of those problems.

if we can run this test_ before_ merging to main, then I think this is a good compromise.

**Comment by cedounet** [comment]
PR done, YOLO...
