### ISSUE TITLE
Link colors look odd in PDF version of book

### ISSUE THREAD

**Issue by hendricius** [hendricius/the-sourdough-framework#142]
Most of the users read the .pdf version of the book on their device. A recent change has made the book look a bit odd in PDF Readers (like my Preview).

Examples:

<img width="730" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/0807e256-2a76-428b-9693-e3897591b022">

<img width="747" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/ef85dc3c-52ae-404b-a28c-4290aedbae5f">

<img width="434" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/c76ddb26-b654-4d61-924d-86d3deea12fa">

I suspect it is `\usepackage[ocgcolorlinks]{hyperref}` that we recently added. What do you think @cedounet?

**Comment by cedounet** [comment]
Yeah, I do not like defaults Colors either, but I like the links to be visible….

1) they will print in black
2) we can change them to something nicer, was planning to do that.  I am just not sure which colours are accessible (colour blinds etc…)

If you prefer same colours as text then fine with me.  This is your call :)

**Comment by hendricius** [comment]
@cedounet maybe blueish color? https://github.com/hendricius/the-sourdough-framework/blob/main/book/book.tex#L20 this one here would be great for all the links :-). Printing in black is great.

**Comment by cedounet** [comment]
and thou shall receive a fix:
https://github.com/hendricius/the-sourdough-framework/pull/144
