### ISSUE TITLE
Possible incorrect percentage range for whole wheat flour ingredient addition

### ISSUE THREAD

**Issue by lrobi2014** [hendricius/the-sourdough-framework#156]
See https://github.com/hendricius/the-sourdough-framework/blob/0a3eb3ec990b8cee515750d144f5b285186575af/book/wheat-sourdough/wheat-sourdough.tex#L190

Should this be 20% - 30%? It seems that that was the range used previously.

**Comment by cedounet** [comment]
Thanks for the report: https://github.com/cedounet/the-sourdough-framework/commit/c3771f12044a54aada6461af1a4c59c2cfbde430
