### ISSUE TITLE
How much starter to use?

### ISSUE THREAD

**Issue by smeredith** [hendricius/the-sourdough-framework#164]
When talking about how much starter to use, you normally talk about how much in relation to total flour.

"If you were to use an extreme value of around 90 % starter based on your flour, there would be very little room for the microorganisms to adjust in the main dough. "

"I’d always be using around 100 g to 200 g of starter for around 1000g of flour (baker’s math: 10% to 20%).
 
But in this instance, you talk about in relation to total dough mass:

"Most bakers use around 20% sourdough starter based on the dough mass. I recommend going much lower, to around 5 to 10%."

Is this last statement an error? Did you mean to use a baker's math percentage here too?

**Comment by hendricius** [comment]
Good catch. Thank you for reporting this!
