### ISSUE TITLE
Confused by bassinage in flow chart

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#182]
![image](https://github.com/hendricius/the-sourdough-framework/assets/134267244/9d6f6c89-292b-4450-bb49-5497d509c9fa)

After adding water kneading or wait 15 min?

**Comment by hendricius** [comment]
Good catch. I must have had too much wine. Fixed in #182

**Comment by cedounet** [comment]
Was depicting the dough taking a 15 min bath😭

**Comment by hendricius** [comment]
@cedounet some people claim this is essential when making Pannetone. It is supposed to remove the acidity from the sourdough starter... I tested it, it doesn't work.
