### ISSUE TITLE
Translate in other language

### ISSUE THREAD

**Issue by Ludo-code** [hendricius/the-sourdough-framework#211]
Hello,

Is it possible to have other version with different language... Like Spain, French, Italian, etc...

**Comment by cedounet** [comment]
Hello,

we discussed that in https://github.com/hendricius/the-sourdough-framework/discussions/87

TL;DR we don’t really have the workflow in place right now and maintaining another language when it is a moving target will be a lot of work.

Now I would love somebody to go ahead and start a translation, technical details can be dealt with after.

**Comment by pacoccino** [comment]
Just started a small script to automatically translate the book with ChatGPT. 
https://github.com/pacoccino/the-sourdough-framework/pull/1/files
It works for now, besides automatic translation is not perfect but at least we have a starting point for many langages quickly. 

Still figuring out how could be the workflow to run, store and build the translations
