### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#212]
In sourdough-starter/sourdough-starter.tex around line 173

"But only the fittest microbes fitting the sourdough's niche are going to survive."

Is that _niche_ or _needs_ ?

Also, aoround line 239:

"I\~also frequently dry it and use it as a rolling agent for pizzas that I\~am making"

What is a rolling agent?

Let me know.. I am rewording that chapter a bit so i can fix it while at it.

**Comment by cedounet** [comment]
@hendricius  any input?

Thanks

C/

**Comment by hendricius** [comment]
@cedounet - sorry, these days have been busy.

1. That is correct. The microbes that are most adapt to fermenting flour win and will outcompete the others.

2. Maybe rolling agent isn't a good word? I use the dried sourdough starter on my pizza peel. It helps that the pizza does not get stuck in the peel.

**Comment by cedounet** [comment]
Not being native I can't really be 100% sure...

**Comment by hendricius** [comment]
@cedounet then I think it's okay. I had a couple of native speakers look over this :-)
