### ISSUE TITLE
Add version with smaller, B&W images for Kindle

### ISSUE THREAD

**Issue by mattsafraid** [hendricius/the-sourdough-framework#216]
I'm following The Bread Code tips and managed to bake nearly-awesome bread by using them. I'm excited about this book and while I wait for the hardcover edition, I'm reading it on my Kindle. 

There are basically two ways to send an external file to a Kindle: First one is plugging the good n' old USB cable, and the second is sending an email to a specific address with the file attached. The second way is constrained to 50MB attached files. 

Today the e-mail method is not possible because the book is bigger than the constraint, due to color images in high resolution.

My suggestion here is to enable the build pipeline to create an ebook with lower resolution images, because all the gorgeous food pictures from culinary books are screwed up in Kindle's B&W screen anyway.

Moreover (and most importantly), that would allow for automation when a new version is pushed to Git - I could then build some dummy robot that checks for updates, downloads the new version and sends it via email. 

Thanks for the awesome content!

**Comment by cedounet** [comment]
Hello,

i am not an ebook user of any sort… is there a need for Colors pics for some format?  And which format do Kindle use? We generate 3 right now… one of them relying on an unsupported tool form Amazon.


Thanks

c

**Comment by mattsafraid** [comment]
Hi, thanks for your answer! 

So for E-ink devices such as the Kindle they are black & white. Please see the attached file, showing a picture of my Kindle with the manually-uploaded .epub file from this repo. 

<img src="https://github.com/hendricius/the-sourdough-framework/assets/21038389/c40f286a-f9b6-43bf-be2f-c3430e3add3a" width=20% height=20%>

[a96ec65f-318d-47f4-ad1d-95909e16cae2](https://github.com/hendricius/the-sourdough-framework/assets/21038389/c40f286a-f9b6-43bf-be2f-c3430e3add3a)

As for the formats, Amazon has retired the proprietary MOBI format (.mobi, .azw) and supports .epub for ebooks as well as other formats for documents and images as .pdf, .doc, and so on. 

List of supported files: 
https://www.amazon.com/gp/help/customer/display.html?nodeId=G5WYD9SAF7PGXRNA

MS Press discontinuing MOBI format: 
https://www.microsoftpressstore.com/promotions/product-announcement-retirement-of-amazon-mobi-ebook-142421

There is an Amazon service that allows to send files up to 200MB to Kindles but using the web interface or some app - https://www.amazon.com/sendtokindle. I can't find a way to use this as an API. 

On the other hand, the .epub files can be read everywhere else (smartphones, tablets, computers...) so it doesn't make sense to replace it by a B&W or reduced image quality. 

So if I may, I suggest the maintenance of current .epub version, and a second .epub file with images in BW with lower resolution.

Also I think it's worth considering the retirement of MOBI formats, as you mentioned they're created with an unsupported tool. 

Best regards,

**Comment by cedounet** [comment]
Good Morning,

I built a version w/o any images and it does not look like images are the only problem here:

With pictures:
```
117M  TheBreadCode-The-Sourdough-Framework.azw3
 57M  TheBreadCode-The-Sourdough-Framework.epub
117M  TheBreadCode-The-Sourdough-Framework.mobi
 58M  TheBreadCode-The-Sourdough-Framework.pdf
```

Without pictures:
```
117M TheBreadCode-The-Sourdough-Framework.azw3
 57M TheBreadCode-The-Sourdough-Framework.epub
117M TheBreadCode-The-Sourdough-Framework.mobi
531K TheBreadCode-The-Sourdough-Framework.pdf
```

the pdf gets clearly smaller > 100 times !,  while the epub looks exactly the same 😨 

I suspect we are embedding fonts in the document.  We should deal with that first, then the pics I think.  

If B&W pics only bring a minor size improvement, I am of the idea of not complicating the build process.

C.

C

**Comment by cedounet** [comment]
So a no picture version would be:

  2.0M book.azw3
  670K book.epub
  2.0M book.mobi

(contrary to what i said in my now deleted comment).

Going B&W (same resolution and size)
 47M  book.epub
 95M  book.mobi 
 95M  book.azw3 

So that might not be enough by itself... Any inputs on resolution would be appreciated.

PS
For future me:
mogrify -set colorspace Gray -separate -evaluate-sequence Mean **/*.jpg

**Comment by cedounet** [comment]
Hello @mattsafraid,

any light you could shed or pointers towards desired pic resolution?

Thanks

C/

**Comment by cedounet** [comment]
@mattsafraid  see https://github.com/hendricius/the-sourdough-framework/tree/bw_ebook great if you could test and give feedbac?
  
too aggressive ? Look at image X or Y they look bad etc..

Thanks

**Comment by cedounet** [comment]
https://github.com/hendricius/the-sourdough-framework/pull/253
