### ISSUE TITLE
Lots of repetition in flatbread section

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#246]
Please have a look at https://github.com/hendricius/the-sourdough-framework/tree/bread-types where I re-ordered the text... i think this is more logical but makes it obvious how much repetition there is between the general flat bread text and the actual receipie.

Let me know what you think..

C

**Comment by hendricius** [comment]
@cedounet I assume #301 is related - or?

**Comment by cedounet** [comment]
It is indeed.
