### ISSUE TITLE
Add dough temperature to the equation in section "11.4.2  OVERFERMENTED"

### ISSUE THREAD

**Issue by nikolanedic** [hendricius/the-sourdough-framework#248]
I know you've written about dough temperature in other places, but it may be misleading if someone stumbles upon this section on its own. If you have high protein flour dough that's 27C and you let it double in size during bulk ferment and then retard it for 15h, chances are it will overproof as it will take longer to cool completely in the fridge. However I don't have any proof for this, it's just a theoretical suggestion :D

**Comment by hendricius** [comment]
Great point. I opened up a PR addressing this. I hope it is clearer now.
