### ISSUE TITLE
Issues with opening up the black & white ebook

### ISSUE THREAD

**Issue by hendricius** [hendricius/the-sourdough-framework#261]
With the latest version of the black & white ebook it seems that I can not open it in apple books. However it works fine with calibre.

Attaching this bug report I received from a user:
<img width="916" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/fbc5ec5d-a30f-4643-997c-358bc68eff94">

Does anyone have an ebook reader and test if it can be opened? Here's the link: https://the-bread-code.io/bw-book.epub

**Comment by cedounet** [comment]
Calibre is all i tested obviously...  Let me have a look.  Does it work on kindle?  Which is all I care

**Comment by cedounet** [comment]
yeah I took too many shortcuts:
❯ epubcheck bw_book.epub
WARNING(PKG-014): bw_book.epub/./bw_book.epub(-1,-1): The EPUB contains empty directory "meta-inf/".
FATAL(RSC-002): bw_book.epub/./bw_book.epub(-1,-1): Required META-INF/container.xml resource could not be found.

Check finished with errors
Messages: 1 fatal / 0 errors / 1 warning / 0 infos

EPUBCheck completed

**Comment by cedounet** [comment]
❯ epubcheck bw_book.epub

[...]

Check finished with errors
Messages: 22 fatals / 381 errors / 0 warnings / 0 infos

EPUBCheck completed

does look exactly as bad as the colour one 😨 ... and it opens in applebook or whatever is the default on Macos

**Comment by hendricius** [comment]
@cedounet can confirm it works now. But I could also reproduce it not working the other day using the one built via the Github action. Let's keep an eye on it. I hope it's not a flake build issue. Thanks for investigating!

**Comment by cedounet** [comment]
let's see what OP thinks...  i am not really sure what i am doing on that one 😺
