### ISSUE TITLE
No flowcharts on ebooks

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#279]
No flowchart is showing up on the book built
- Does not work on MacOS
- Does not work on my debian (testing) machine anymore
- Does not work on the CI.  It used to...

All svg are empty (debian)
`❯ ls -1 --size -h book*svg
0 book0x.svg
0 book10x.svg
0 book11x.svg
0 book12x.svg
0 book13x.svg
0 book14x.svg
0 book15x.svg
0 book16x.svg
0 book17x.svg
0 book18x.svg
0 book1x.svg
0 book20x.svg
0 book21x.svg
0 book22x.svg
0 book23x.svg
0 book2x.svg
0 book3x.svg
0 book4x.svg
0 book5x.svg
0 book6x.svg
0 book7x.svg
0 book8x.svg
0 book9x.svg`

**Comment by hendricius** [comment]
@cedounet any chance you can install Docker on your local machine? Then we at least have the same environment. Docker for desktop.

**Comment by cedounet** [comment]
I can try that when I am back... i got ebooks to work (i.e. show flowcharts) on my debian machine though.  So likely a tool problem.

debian looks like:
`<?xml version='1.0' encoding='UTF-8'?>

<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='0pt' height='0pt' viewBox='0 0 0 0'>
<g id='page1' transform='matrix(1.4 0 0 1.4 0 0)'/>
</svg>`

MacOS:
`The old, written in PostScript, PDF interpreter has been removed entirely.
You should cease using -dNEWDPF as it has no effect n<?xml version='1.0' encoding='UTF-8'?>

<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='0pt' height='0pt' viewBox='0 0 0 0'>
<g id='page1' transform='matrix(1.4 0 0 1.4 0 0)'/>
</svg>`

**Comment by cedounet** [comment]
CI is using
```
dvisvgm --version
dvisvgm 3.0.3
```

**Comment by cedounet** [comment]
After https://github.com/hendricius/the-sourdough-framework/pull/281

we are on
```
dvisvgm --version
dvisvgm 3.1.2
```
for the CI

Does not seem to help a lot though, erros from calibre here and no image.

```Failed to read from book file: OEBPS/book0x.svg with error: [Errno 2] No such file or directory: '/home/ced/.cache/calibre/ev2/f/c1-69kofpth/OEBPS/book0x.svg'
Failed to read from book file: OEBPS/book2x.svg with error: [Errno 2] No such file or directory: '/home/ced/.cache/calibre/ev2/f/c1-69kofpth/OEBPS/book2x.svg'
Failed to read from book file: OEBPS/book3x.svg with error: [Errno 2] No such file or directory: '/home/ced/.cache/calibre/ev2/f/c1-69kofpth/OEBPS/book3x.svg'
Failed to read from book file: OEBPS/book4x.svg with error: [Errno 2] No such file or directory: '/home/ced/.cache/calibre/ev2/f/c1-69kofpth/OEBPS/book4x.svg'
Failed to read from book file: OEBPS/book5x.svg with error: [Errno 2] No such file or directory: '/home/ced/.cache/calibre/ev2/f/c1-69kofpth/OEBPS/book5x.svg'
Failed to read from book file: OEBPS/book6x.svg with error: [Errno 2] No such file or directory: '/home/ced/.cache/calibre/ev2/f/c1-69kofpth/OEBPS/book6x.svg'
```

**Comment by hendricius** [comment]
Seems like it can't find the resources somehow, right?

**Comment by cedounet** [comment]
Looks like svg files are not being created for some reason?

**Comment by hendricius** [comment]
@cedounet this can be closed right?

**Comment by cedounet** [comment]
I think so but I have not checked yet… if you have please do :)

**Comment by cedounet** [comment]
https://github.com/hendricius/the-sourdough-framework/pull/287 Now verified (with Calibre..)
