### ISSUE TITLE
Docker image build should be done before various books compilation

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#282]
Right they are run in parallel… so guaranteed that a change to the docket image will b not be taken into account before build/release next commit.

**Comment by hendricius** [comment]
Agreed. That should ideally be built before.

**Comment by hendricius** [comment]
Priority probably not so high - as we probably do not change the actual docker image that often 😅 . But agreed - if this happens, we need to keep it in mind. If somebody with docker skills want's to have a go please be my guest!

**Comment by cedounet** [comment]
We should have this image cached?  I am not sure why we would build every time.

also we should probably pin the versions… that recent regression was quite annoying.

**Comment by hendricius** [comment]
Agreed - it was super annoying to pin point this down. Thanks for the sherlock support.

Each step in the Dockerfile is cached - so yep - it's probably not going to take that long. Ideally each commit should have its own image and then one more image for the main branch.

**Comment by hendricius** [comment]
I propose we build a new image on every push to a branch? Ideally then this image should also then build the book once and attach it as artefacts to the PR? And then one in main that is always the latest version of everything after the merge?

**Comment by hendricius** [comment]
Ok - then it would make sense we just build one image and freeze it for each branch? The image would be tagged with the branch and we can restore it later, the dependencies are frozen in the image. If nothing changes - the build process is cached for each step in the dockerfile, so only if something changes in the docker file - the image is also being updated.

**Comment by hendricius** [comment]
Agreed 👍 . Reproducibility is important.

Not sure if I can control the "nothing changed" in the build process. I will have a look 😎 . Either way - since the dockerfile has not changed - it will take all the dependencies from the github actions cache and not take long to build again. It will then also take exactly the previous versions and not update dependencies.

**Comment by hendricius** [comment]
#299  and #300
