### ISSUE TITLE
Website looks weird on iOS / firefox

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#302]
and on Firefox/linux

**Comment by cedounet** [comment]
![IMG_3264](https://github.com/hendricius/the-sourdough-framework/assets/134267244/e3d8cb31-db62-4f38-9338-c5c313571adf)

**Comment by hendricius** [comment]
Thanks. It seems something in general broke the website:

<img width="1153" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/017b6bfd-ed7f-4829-8aa1-8b1dde245fdd">

I will investigate 😎

**Comment by hendricius** [comment]
It seems like the book.css doesn't have the full content somehow.

**Comment by hendricius** [comment]
... Works locally. I will test on my Linux system and report back.

**Comment by cedounet** [comment]
you might want to have a look at http://tug.tug.org/TUGboat/tb44-2/tb137island-docker.pdf ... Google some more there are slides and Youtube video.  The repo is at https://islandoftex.gitlab.io/ most interesting for us is the docker image one...

Usual disclaimer, I know nothing about Docker so feel free to ignore.

**Comment by hendricius** [comment]
@cedounet I went back in time commit by commit, seems like 4b4d80d231976059b8d35337b57b0b1fe63aaba7 is breaking it, PR #301 

I see a lot of warnings when building the doc:

<img width="598" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/edefae04-9e33-4728-b1e3-53b962e264eb">

**Comment by hendricius** [comment]
@cedounet I can't really see though what's the issue. Maybe revert the PR first then try a little more relaxed with time?

**Comment by hendricius** [comment]
@cedounet see #304. I found the problem. The problem is when you build the pdf and then directly after the website: `make bake && make website`. For some reason I need to clean the build with `mrproper`. I fixed it in the PR. Also added an error in case the website building fails.
