### ISSUE TITLE
Kobo flowchart overflow

### ISSUE THREAD

**Issue by Apostolique** [hendricius/the-sourdough-framework#313]
Now that #312 is in, I can confirm that the book can be opened on my Kobo device using the new builds on the site.

One issue that I noticed is that flowcharts are rendering way too big which makes them overflow the device screen. For example flowchart 4 and 5:

![291104609-82e4a62a-0d6e-4473-a573-3ee73e13548f](https://github.com/hendricius/the-sourdough-framework/assets/2766423/9d53ef00-9167-46f9-953a-ba58e73dc451)
![291104540-c4aef79d-ad93-4d57-8d10-9707b308d6e6](https://github.com/hendricius/the-sourdough-framework/assets/2766423/e242f02d-d45e-4b70-bd6c-3410cc0d8a30)

Figure 1.2 showing the timeline history is fine though.

Another issue is that the book doesn't display a cover page.

**Comment by cedounet** [comment]
Are they actually showing in colour or you did a look-alike screenshot?

**Comment by cedounet** [comment]
Hello @Apostolique  I did a trial in https://github.com/hendricius/the-sourdough-framework/tree/313-kobo-flowcharts only the liquid starter conversion has it though... Let me know if that works?

**Comment by cedounet** [comment]
Apologies i rushed too much yesterday... https://github.com/hendricius/the-sourdough-framework/tree/313-kobo-flowcharts now has the code i actually wanted you to test.

**Comment by Apostolique** [comment]
Hey, sorry for the delay, only got to this now.

I generated the ebook. Figure 3.1 and 3.2 look good. Flowchart 1 overflows the bounds of the Kobo.

**Comment by cedounet** [comment]
On Wed, Dec 20, 2023 at 01:22:02AM -0800, Jean-David Moisan wrote:
> Hey, sorry for the delay, only got to this now.
> 
> I generated the ebook. Figure 3.1 and 3.2 look good. Flowchart 1
> overflows the bounds of the Kobo.

OK thanks that is really helping.  It is time to pack for the year here
though, so will probably be in Jan or Feb when I look at it.

Have a great Christmas and new year everyone.

Ced

**Comment by cedounet** [comment]
@Apostolique  there is a tentative fix, should work... If it does @hendricius I would need you to review because css is your favourite thing in life, not mine :black_cat:

**Comment by Apostolique** [comment]
Everything looks good. Testing the book just now.

**Comment by cedounet** [comment]
https://github.com/hendricius/the-sourdough-framework/pull/338

**Comment by cedounet** [comment]
@Apostolique  I believe this is not fixed in main.  Please let me know if not.

**Comment by Apostolique** [comment]
Did you want me to test again? I had sort of forgotten about this.

**Comment by cedounet** [comment]
I assumed it works as you did not complain :)  I can’t test myself so I merged the patch… assuming it will just work.

**Comment by Apostolique** [comment]
Sorry it took me this long to check but I can confirm that the fix worked on the whole book. I tested the BW version from the CI.
