### ISSUE TITLE
Improve pH meter description

### ISSUE THREAD

**Issue by hendricius** [hendricius/the-sourdough-framework#332]
<img width="953" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/b7b17ab3-f47c-414c-91c5-6f5b175cb0d2">

**Comment by hija** [comment]
Unfortunately, I cannot give the final answer to the question, but a few months ago I did some research and here is what I wrote down in my notebook. Maybe it's a starting point for further research :)

- There are pH meters which are certified for liquid and semi-solid media, e.g. [testo 206-pH2](https://www.testo.com/en-UK/testo-206-ph2/p/0563-2062) (or testo 205)
  - The [information for this pH meters](https://static.testo.com/image/upload/HQ/productfinder-ph-en.pdf) specifically mention dough as one application
  - These information show that not every pH electrode is suitable for measuring the pH value of a dough

**Comment by hendricius** [comment]
Thanks for the comment! I updated the text a bit to make it clearer :-). I did not want to mention a specific pH meter to not advertise a product.
