### ISSUE TITLE
Build time on CI went to the roof

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#337]
Between 25 min and 1 hour?  I understand we build a new docker image every time... Surely there is lot we could cache?

**Comment by hendricius** [comment]
Sounds good - I will create a PR soon!

**Comment by cedounet** [comment]
modulo https://github.com/hendricius/the-sourdough-framework/issues/349 this is better when pushing to branch or making a PR.

Merge to main still is a problem by the look of it (>30 min)

**Comment by hendricius** [comment]
Closing this for now. Feel free to open again!
