### ISSUE TITLE
How do we get reviews from the printed book

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#342]
There were tons of reviews… is there any way to get a list of them?

I tried copy pasting from some versions I had lying around and that is painful as2 columns become a single line…

Thanks

Ced
PS: not even sure where final pdf is, if I was masochist enough to do it manually…

**Comment by hendricius** [comment]
What kind of reviews would you like? Just general if people like the content? I could ask to submit them via a form :). Maybe it would be best though to wait until everyone has received their copy. I hope in in the next 2-3 weeks.

Here's the direct link to download the design edition: https://downloads.the-bread-code.io/release/book-hardcover.pdf

**Comment by cedounet** [comment]
I meant the changes… I am sure people will love it :)

**Comment by hendricius** [comment]
Yes 100%. So I just got the full designer's file and can start working on it soon. Currently on my priorities:

1. Finish shipping the international book orders - annoying issues with customs.
2. Design update for the sourdough framework website
3. Eat some french cheese with a bit of wine roasted in the oven
4. Update the free version with the new illustrations 👍 . Maybe we can ask someone in the community to help too? It's mostly just copy pasting in some graphics.

**Comment by cedounet** [comment]
No sweat…  but they were some great grammar and clarity changes in the text.

thing is that this is not just copy paste, at least with my pdfviewer… it copies lines and ignores the columns layout effectively mangling it all together.  Yes it is but also not it is not automatic.

shipping the book should be your priority ofc.

PS:
> Eat some french cheese with a bit of wine roasted in the oven

 are you actually roasting wine in the oven?  As a French man there is only so much I can forgive.

**Comment by hendricius** [comment]
Agreed! We can make a community effort out of this to go through the PDFs and followup with a few PRs.

Cheese - yep - my french colleague has recommended this to me 🤣. It's a `Langres`
