### ISSUE TITLE
Typo in stiff starter usage

### ISSUE THREAD

**Issue by vtan82** [hendricius/the-sourdough-framework#348]
Hey there,

Love your book.

Found a issue with your % of stiff starter here:

`When using a stiff starter, use around 1 % to 20 % starter for your dough. This depends
on the ripeness of your starter. In summer I typically use around 10 % and in winter
around 20 %.`

I assume you meant 10% and not 1%.

Cheers

**Comment by hendricius** [comment]
Thanks for the bug report! I clarified it a bit in the attached PR. Can you check if you like it more?

It is indeed 1 to 10% in summer. I go way lower in starter amounts compared to winter 😎

**Comment by hendricius** [comment]
Closing for now. Feel free to reopen! Thanks for the report.
