### ISSUE TITLE
Text on back of hardcover book may be oriented wrong.

### ISSUE THREAD

**Issue by ghakfoort** [hendricius/the-sourdough-framework#360]
when the hardcover book lies on the table and you take a look, you can read the front but the text on the back is upside down. I also compared it to other books I have and this one is the only one with the text on the back upside down. If the book is on the shelf, it makes it more convenient if the backside text is oriented the same way on all books. No ideas about "book rules" but it may be something to take in mind for a next version of the hardcover book. No big deal dough ;)

**Comment by cedounet** [comment]
Got pictures?  Mine looks very fine…. Thanks!

**Comment by cedounet** [comment]
The side… yes most English books (but not all) have it the other way around.

now you can feel the pain of multilingual people with OCD :)
![IMG_4613](https://github.com/hendricius/the-sourdough-framework/assets/134267244/fa8dfeba-131c-4c19-94e2-04a3b370e4cf)

**Comment by ghakfoort** [comment]
I think I need a book about making books to understand the process of book making. 🤣 anyway I think we can close this one 👌

**Comment by cedounet** [comment]
Not much we can do on the open source version… but I agree @hendricius should feed that back to the design house for next batch…
