### ISSUE TITLE
Dry sourdough maintenance

### ISSUE THREAD

**Issue by Drazhar** [hendricius/the-sourdough-framework#361]
Hey

First of all, I really like your guide and Youtube Channel and quite often like to bake bread/pizza. My issue is with consistency, I don't like to **have to** bake and maintain my sourdough. That's also the reason why I stopped using sourdough after 2-3 months and gravitated towards poolish/biga with tiny amounts of commercial yeast when I bake.

But in general I prefer to use a sourdough. Recently I saw this method of maintaining the sourdough:
https://www.youtube.com/watch?v=POD2gRL799Q

In short: Instead of feeding with flour and water, just the flour is added, which results in a very dry "starter". This can then be stored in the fridge for quite a long time. Before baking just add the water a day before and have a ready starter the next day. This method seems to be very attractive and simple! I yet have to test it, but first my new sourdough has to ripe. The issues which come to my mind are:
- How active is the starter with this method after just 1 feeding?
- How sour will it be after a longer storage? Storing a liquid starter (100% hydration) in the fridge had the tendency to make it too sour for my taste.

Now to my suggestion: If this method works, it would be a great addition to your maintenance section/flowchart.

Keep up the great work and best regards
Philip

**Comment by hendricius** [comment]
Hey Philip,

thanks for the issue.

That method could work and might prevent a layer of mild forming on top of a dried starter in the fridge. However - the safest bet is to just freeze some of your active starter for later use - that way you definitely have 0 maintenance and it should work directly out of the freezer. Plus you do not have the danger of mold forming.

https://www.the-sourdough-framework.com/Makingasourdoughstarter.html#maintenance

Another option is to add a layer of water on top of your starter. This way the starter will not dry out (no mold). It's sort of like pickled food. In that option you regardless have to feed the starter once after extended fridge times. The starter continues to ferment in the fridge at low temperatures.

Hope this helps!
