### ISSUE TITLE
Booklet missing from main page

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#370]

**Comment by hendricius** [comment]
@cedounet main page in the book?

**Comment by cedounet** [comment]
I meant README.. apologies

If you prefer a very short version (about 10 pages) with main flowcharts and crucial informations needed while you are in the kitchen, we also provide a "too long;didn't read" version you could print. Having read the full book is highly recommended to understand this leaflet:

[Download a condensed version] (https://www.the-bread-code.io/booklet.pdf)

**Comment by hendricius** [comment]
<img width="1001" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/7076f895-b52d-4a59-9bee-3142efdcc943">

It's in there right? 😎

**Comment by hendricius** [comment]
We could maybe rename to: Download the condensed booklet version

**Comment by hendricius** [comment]
Oh and yep - that's also missing from the website.

**Comment by cedounet** [comment]
![Uploading IMG_4667.jpeg…]()

**Comment by hendricius** [comment]
Ooops. That's fixed now 😎
