### ISSUE TITLE
Language tool

### ISSUE THREAD

**Issue by szepeviktor** [hendricius/the-sourdough-framework#374]
Please use a language tool when writing text for a book.
e.g. DeepL, Hunspell or Grammarly

**Comment by cedounet** [comment]
Yeah I had a branch with aspell in make check at some point but it gave soo many false positive that I never merged it.

if hunspell is open source, packaged in Debian and we have a way to limit false positive then I am all for it adding it back to the makefile.

Language is en-US-UTF-8

Thanks

**Comment by szepeviktor** [comment]
@cedounet You can get dictionaries from LibreOffice/dictionaries
Hunspell from `apt-get install hunspell`
then `hunspell -d path to/libreoffice-dictionaries/en/en_US -l` with optional local dictionary: `-p hunspell.txt` (1 word per line)

**Comment by cedounet** [comment]
Thanks.

how many false positive when ran accross all tex files and eventually comments in code ?

**Comment by szepeviktor** [comment]
I've used `typos` in #375.

**Comment by szepeviktor** [comment]
```
cat $(git ls-files '*.tex')|sed 's/\\[a-z{}]\+//g'|../hunspell-en_US|sort -f|uniq -i|grep -v '^[0-9]'
```
300 words including proper nouns, non-English words, an British words.

**Comment by hendricius** [comment]
I have been using Grammarly in my IDE.
