### ISSUE TITLE
Sources run off page in PDF

### ISSUE THREAD

**Issue by sawft99** [hendricius/the-sourdough-framework#392]
![image](https://github.com/user-attachments/assets/7796da08-aefc-4e57-8755-edd71bbb1b4e)

**Comment by hendricius** [comment]
Thanks for the report!

@cedounet looking at you - any idea what might be wrong? 🙈

**Comment by cedounet** [comment]
I will have a look in a few days… hyperef does automatic cutting but maybe not in conjunction with latexbib? 

If they don’t do it then it must be another can of worms…

**Comment by cedounet** [comment]
It was indeed a can of worms..  but everything was explained in hyperref pacakge documentation

7.12
Experimental option ‘ocgcolorlinks’
The idea are colored links, when viewed, but printed without colors. This new experimental option
‘ocgcolorlinks’ uses Optional Content Groups, a feature introduced in PDF 1.5.
A better implementation which hasn’t the disadvantage to prevent line breaks is in the ocgx2
package. Check its documentation for details how to use it.

• The option must be given for package loading: \usepackage[ocgcolorlinks]{hyperref}

**• Main disadvantage: Links cannot be broken across lines. PDF reference 1.7: 4.10.2 “Making**
Graphical Content Optional”: Graphics state operations, such as setting the color, ..., are
still applied. Therefore the link text is put in a box and set twice, with and without color.

I think it is safe to remove it... few people will print it anyway I believe, worst that can happen is link in colour anyway

**Comment by cedounet** [comment]
https://github.com/hendricius/the-sourdough-framework/pull/400
