### ISSUE TITLE
Flowcharts and pictures should follow same numbering convention

### ISSUE THREAD

**Issue by cedounet** [hendricius/the-sourdough-framework#395]
Pics are chapter.pic numbering so 3.1, for chapter 3 and first pic in that chapter…. While flowcharts only increase 1, 2, 3 

I would propose we align flowcharts to pics? What do you think ?

**Comment by ramink** [comment]
I would say that having the same convention actually might make things more difficult, in a way. If you have a photo 3.2 vs table 3.2 vs flow chart 3.2 and so on, it might make things more easily misidentified. But Photo 3.2 vs table A vs flow Chart i is less prone to cross-contamination.

Of course, you quickly run out of distinct numbering conventions. But I just wanted to put the thought out there.

Perhaps a good compromise would be to use the same numbering system, but only allow each number to be used once. So if you had a photo 3.2, then you couldn't have a table 3.2. So photo 3.2, table 3.3, etc.

Fleshing this out even more, I'd probably reserve the numbers for sections and sub-sections, then add letters for the elements. So you'd have as an outline:

3. Making A sourdough starter
3.1 Baker's math
- Table 3.1A (first BM example)
- Table 3.1B (second BM example)
3.2 The Process of making a starter
- Figure 3.2A (active sourdough starter pic)
- Flow chart 3.2B (what is now flow chart 1)

As a final thought, you might find a generic term for all these things. So maybe they'd be Sidebar 3.2A and Sidebar 3.2B.

**Comment by cedounet** [comment]
I do want table, figure and flowchart to be different and have their own list of at the end of the book.  That is on purpose.

I need to think about your idea, using a different numbering (letter, roman, Arabic) should not be hard but not sure that would be logical.  I will also have a look at how books do it as well, other people did think about it before I would hope :)

Tables and figures follow same convention… and that is TeX code I did not write so probably more correct than flowcharts one..

**Comment by cedounet** [comment]
Add  a though and "industry standard" of using "photo 3.2 vs table 3.2 vs flow chart 3.2"  is the most logical.  They are different entities like a sheep and a cow, so cow#7 and sheep#7 are not confused, same here I think.

Fixed in https://github.com/hendricius/the-sourdough-framework/pull/new/flowcharts_numbering

**Comment by ramink** [comment]
The confusion is not huge, but look at the situation now where we have flowchart 3.2 in section 3.3. I would argue that this creates a mental stumble/irritation that would be avoided if that was flowchart 3.3.A. At least you'd know exactly what section to find any given sidebar item in.

It's OK to have Picture 3.3.A vs Flowchart 3.3.A, but flowchart 3.2 in section 3.3 is a bit problematic. It's not a huge issue, though, to be honest! So I'm happy to leave this here, especially if implementing the .A scheme is tricky.
