### ISSUE TITLE
Car Tire

### ISSUE THREAD

**Issue by JRichardH** [hendricius/the-sourdough-framework#52]
7.4 Hydration 

-- The stiff dough is a car tire. The yeast has a much harder time inflating the care tire compared to the balloon. That’s because the rubber of the car tire is much more elastic.

++ The stiff dough is like a car tire. The yeast has a much harder time inflating the car tire compared to the balloon. That’s because the rubber of the car tire is much less elastic.

**Comment by hendricius** [comment]
Thank you! Good catch.
